[enhancement] Adding non-fatal errors to tasks
checkupjs/checkup pull request #1137
Opened 2021-11-15 21:27 UTC by carakessler

## Rationale: 
Previously, when a single file could not be parsed correctly, the entire eslint-disable task would fail. We want to notify our consumers when a file can not be parsed, or when any error occurs when analyzing a single file, but we dont necessarily want that to cause the whole task to fail. It is now up to the author of a task whether they just want to throw an error when a failure is caught, or just add a nonFatalError, which are all collected at the end and pushed to the `toolExecutionNotifications`.

## Implementation: 

Added new public function `addNonFatalError` to base-task, and collected the nonFatalErrors in task-list with the other (fatal) errors. This approach pushes the responsibility of handling failures in the analyzers onto the task authors, giving them full control of how they want to handle what happens when a file cant be analyzed (for some tasks, I imagine failure to read/parse a file to be fatal, and for the desired behavior to be a task erroring out completely). With this change, made required changes to eslint-disable task (the only task using the AstAnalyzer right now).

2021-11-15 22:16 UTC, scalvert requested changes

2021-11-15 22:16 UTC, scalvert commented on packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
> +    expect(task.nonFatalErrors![0]).toMatchInlineSnapshot(
I think you can just use `toEqual` in this case, which would allow you to avoid the eslint disable (ironic this is in a PR related to eslint-disable stuff).

2021-11-15 22:16 UTC, scalvert commented on packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
> +            this.addNonFatalError(error as Error);
I'd probably just throw a new error instead, rather than mutating the current error's message.

2021-11-15 22:16 UTC, scalvert commented on packages/cli/src/task-list.ts
> +      this.addErrors(task.fullyQualifiedTaskName, task.nonFatalErrors);
Should this always be called? What if there are no fatal errors?

2021-11-15 22:38 UTC, carakessler commented on packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
> +    expect(task.nonFatalErrors![0]).toMatchInlineSnapshot(
lol meta!! good call, fixing

2021-11-15 22:39 UTC, carakessler commented on packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
> +            this.addNonFatalError(error as Error);
if i do that, i would lose the stack trace, no?

2021-11-15 22:40 UTC, carakessler commented on packages/cli/src/task-list.ts
> +      this.addErrors(task.fullyQualifiedTaskName, task.nonFatalErrors);
then it would be called with an empty array, and nothing would happen. I can wrap this in an `if (task.nonFatalErrors.length > 0)` if you'd prefer

2021-11-15 22:44 UTC, scalvert commented on packages/cli/src/task-list.ts
> +  }
Let's change this to 

```suggestion
  private addErrors(taskName: TaskName, errors: Error | Error[]) {
    if (!Array.isArray(errors)) {
      errors = [errors];
    }
  
    this._errors.push(
      ...errors.map((error) => {
        return {
          error,
          taskName,
        };
      })
    );
  }
```

and then just delete the `addError` function.

2021-11-15 22:48 UTC, carakessler commented on packages/cli/src/task-list.ts
> +  }
lol just did exactly that but no mutation and with a ternary so #oneline ;) updating

2021-11-16 00:27 UTC, scalvert commented on packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
> +            this.addNonFatalError(error as Error);
This is true, and since we're wanting to preserve that stack to ultimately output it in the SARIF log, we should keep it this way.

2021-11-16 00:28 UTC, scalvert commented on packages/cli/src/task-list.ts
> +      this.addErrors(task.fullyQualifiedTaskName, task.nonFatalErrors);
No it's fine, so long as it's not actually adding any errors, which it doesn't. Thanks for clarifying.

2021-11-16 00:52 UTC, scalvert approved these changes

2021-11-16 00:52 UTC, merged