Fixing SARIF log so that each location is mapped to one Result
checkupjs/checkup pull request #781
Opened 2020-11-23 19:18 UTC by carakessler

Even though locations is technically a Location[], if you read the SARIF spec it says that The locations array SHALL NOT be used to specify distinct occurrences of the same result which can be corrected independently.

Modifying tasks to return one Result per location.

Also renamed `toJson` to `appendCheckupProperties` because the name `toJson` made no sense :) In the future, I would love if we could remove this extra call all together, but that may have to involve putting the builders in the base class (or passing in all 4 properties we need to all the builders) but wanted to do that as a follow up to simplify this 

https://docs.oasis-open.org/sarif/sarif/v2.0/csprd02/sarif-v2.0-csprd02.html#_Toc10127841

2020-11-23 23:57 UTC, scalvert requested changes

2020-11-23 23:57 UTC, scalvert commented on packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
> +    ).map((result) => this.appendCheckupProperties(result));
We seem to do this pattern a lot, where we `buildResultsFromProperties` and then we `map` `result` over that. Should we consider combining these, like have `buildResultsFromProperties` take `result` and `map` internally?

2020-11-23 23:57 UTC, scalvert approved these changes

2020-11-23 23:57 UTC, scalvert commented on packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
> +    ).map((result) => this.appendCheckupProperties(result));
I'm fine if you want to do this in a follow up.

2020-11-24 01:06 UTC, carakessler commented on packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
> +    ).map((result) => this.appendCheckupProperties(result));
i feel like the better way to fix this is:  

```
Also renamed toJson to appendCheckupProperties because the name toJson made no sense :) 
In the future, I would love if we could remove this extra call all together,
but that may have to involve putting the builders in the base class (or passing in all 4 
properties we need to all the builders) but wanted to do that as a follow up to simplify this
```

thoughts?

2020-11-25 00:36 UTC, scalvert commented on packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
> +    ).map((result) => this.appendCheckupProperties(result));
Ya either works. Reducing repetitive code would really be the goal here.

2020-11-25 00:36 UTC, merged