Adding task to run ember-template-lint
checkupjs/checkup pull request #793
Opened 2020-12-02 16:04 UTC by carakessler

This task is very similar to eslint-summary, but runs ember-template-lint instead of eslint.

2020-12-02 17:09 UTC, scalvert requested changes

2020-12-02 17:09 UTC, scalvert commented on packages/cli/src/reporters/console-reporter.ts
> +      let totalCount = sumOccurrences(groupedTaskResultsByLintRule);
Can we sort these descending, so that the higher number of occurrences are at the top descending? This makes it really easy to see which ones are violating more than others.

2020-12-02 18:38 UTC, carakessler commented on packages/cli/src/reporters/console-reporter.ts
> +      let totalCount = sumOccurrences(groupedTaskResultsByLintRule);
good call -  fixed it

```
=== Linting

Template Lint Summary

Errors 252

■ require-button-type (70)
■ require-valid-alt-text (57)
■ link-rel-noopener (35)
■ no-invalid-interactive (33)
■ link-href-attributes (24)
■ no-quoteless-attributes (16)
■ simple-unless (5)
■ no-inline-styles (5)
■ no-triple-curlies (4)
■ no-negated-condition (1)
■ table-groups (1)
■ no-extra-mut-helper-argument (1)


Eslint Summary

Errors 24

■ no-prototype-builtins (20)
■ no-redeclare (3)
■ no-setter-return (1)

```

2020-12-03 22:24 UTC, scalvert commented on packages/cli/src/reporters/console-reporter.ts
> +      let totalCount = sumOccurrences(groupedTaskResultsByLintRule);
thank you!

2020-12-03 22:24 UTC, merged