Adding functionality for pretty formatter to write to a file
checkupjs/checkup pull request #941
Opened 2021-04-19 22:49 UTC by carakessler

With this refactor, the ConsoleWriter can operate in two modes. 1) write to console directly and 2) append content that wouldve been written to console to a string.
This way, the pretty formatter can write its contents to a txt file, instead of just printing to console.

This change makes it so that no two cli options are mutually exclusive! All format options work with the ouput-file option

2021-04-19 22:51 UTC, carakessler commented on packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
> -    expect(result.sort()).toMatchInlineSnapshot(`
this test was hella flaky due to the random ordering of the JSON. future refactorings with the sarif matcher should fix this, but wanted to put in a patch for now and sort the results so they didnt come back in random orderings each time they were run

2021-04-19 22:56 UTC, scalvert commented on packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
> -    expect(result.sort()).toMatchInlineSnapshot(`
Yep, this is why I'm working so hard right now on this `@microsoft/jest-sarif` matcher library!

2021-04-19 23:38 UTC, scalvert requested changes

2021-04-19 23:38 UTC, scalvert commented on packages/cli/__tests__/cli-test.ts
> +    let outputPath = output.split(':')[1].trim(); // output will be a string followed by ':' then the file path
I think you could just extend the regex below, or in fact wouldn't it work as is right now?

2021-04-19 23:38 UTC, scalvert commented on packages/cli/__tests__/cli-test.ts
> +    let outputPath = output.split(':')[1].trim(); // output will be a string followed by ':' then the file path
Same as above?

2021-04-19 23:38 UTC, scalvert commented on packages/cli/src/formatters/file-writer.ts
> +}
Any reason not to just combine these into one, and pass in the extension?

2021-04-19 23:38 UTC, scalvert commented on packages/cli/src/formatters/formatter-utils.ts
> +export function renderActions(actions: Action[], consoleWriter: ConsoleWriter): void {
Same comment re: `FormatOptions`.

2021-04-19 23:38 UTC, scalvert commented on packages/cli/src/formatters/formatter-utils.ts
> +export function renderInfo(info: CheckupMetadata, consoleWriter: ConsoleWriter) {
Same comment re: `FormatOptions`.

2021-04-19 23:38 UTC, scalvert commented on packages/cli/src/formatters/formatter-utils.ts
> +export function renderLinesOfCode(info: CheckupMetadata, consoleWriter: ConsoleWriter) {
Same comment re: `FormatOptions`.

2021-04-19 23:38 UTC, scalvert commented on packages/cli/src/formatters/formatter-utils.ts
> +export function renderCLIInfo(info: CheckupMetadata, consoleWriter: ConsoleWriter) {
Same comment re: `FormatOptions`.

2021-04-19 23:48 UTC, carakessler commented on packages/cli/src/formatters/file-writer.ts
> +}
there is some duplication here, but the writing calls a different function (`writeFileSync` vs `writeJsonSync`, and we need to call `stripAnsi` for the txt one. I call pull the consoleWriting out into another function tho to remove that duplication

2021-04-19 23:51 UTC, carakessler commented on packages/checkup-plugin-ember/src/formatters/ember-octane-migration-status-formatter.ts
> +export function format(taskResults: Result[], consoleWriter: ConsoleWriter) {
I understand the value of adding some abstraction here to prevent having to change all these signatures if we need to pass more data, especially since we're knocking on the door of 1.0.0, and these changes would be backwards incompat to other plugins' formatters. 

My only concern with what you proposed here is that the `ConsoleWriter` isn't really a `FormatOption`. The writer is in fact NOT optional ;) 
What do you think of calling the interface `FormatTools` or `FormatUtils` instead?

2021-04-19 23:53 UTC, carakessler commented on packages/cli/__tests__/cli-test.ts
> +    let outputPath = output.split(':')[1].trim(); // output will be a string followed by ':' then the file path
Imo its cleaner and simpler to just split on the `:` than include the whole output string in the regex here. Additionally, if the prose of the output string changes, we wont have to change the test - we only care what happens after that output string (which is the file path). Thoughts?

2021-04-20 00:04 UTC, scalvert commented on packages/checkup-plugin-ember/src/formatters/ember-octane-migration-status-formatter.ts
> +export function format(taskResults: Result[], consoleWriter: ConsoleWriter) {
It is options, depending on what perspective you have. For us, we provide the writer option, which would be required in the interface. Since we're passing the value into this function, it'd always be 'filled in'. 

If you're that opposed to options, can we call it args and `FormatArgs`?

2021-04-20 00:06 UTC, scalvert commented on packages/cli/__tests__/cli-test.ts
> +    let outputPath = output.split(':')[1].trim(); // output will be a string followed by ':' then the file path
But you don't need to include the string in the regex. The regex is `/^(.*)\/my-checkup-file.json/`, which would match any char preceding the path. 

`Whatever we want this to be can go here: some-path/my-checkup-file.json` matches right now...

2021-04-20 00:07 UTC, scalvert commented on packages/cli/src/formatters/file-writer.ts
> +}
Why not just have a single function they both use, and each calls that? You can have a param to `stripAnsi` that's a bool?

2021-04-20 00:11 UTC, carakessler commented on packages/checkup-plugin-ember/src/formatters/ember-octane-migration-status-formatter.ts
> +export function format(taskResults: Result[], consoleWriter: ConsoleWriter) {
I like that, making the change now

2021-04-20 00:57 UTC, carakessler commented on packages/cli/src/formatters/file-writer.ts
> +}
If I call `writeFileSync` with JSON, I need to JSON.stringify it, which removes the nice formatting and such. I still collapsed the two functions and just added some conditionals inside one writer function called `writeResultFile`

2021-04-20 01:07 UTC, carakessler commented on packages/cli/__tests__/cli-test.ts
> +    let outputPath = output.split(':')[1].trim(); // output will be a string followed by ':' then the file path
Ah the regex was failing because there is now a newline and `.` doesnt count those. The regex works if i change it to `(/^([\S\s]*)\/my-checkup-file.json/);`, but then if I want to check the files existence I still think the best way would be to split at the `:`, unless you have a better idea for that?

2021-04-20 17:36 UTC, scalvert commented on packages/cli/__tests__/cli-test.ts
> +    let outputPath = output.split(':')[1].trim(); // output will be a string followed by ':' then the file path
If you want to check for the file, you can change the regex to specifically match the group, right? The reason I'd rather do this is doing splits and trims is very messy and error prone, and we've been trying really hard to stabilize the tests. I think modifying the regex could allow you to absorb more of that variability than doing string manipulations.

2021-04-20 17:37 UTC, scalvert commented on packages/checkup-plugin-ember/src/formatters/ember-octane-migration-status-formatter.ts
> +export function format(taskResults: Result[], formatArgs: FormatArgs) {
Somewhat of a nitpick, but I'd probably just name this `args`, so that the subsequent call is a bit cleaner. I don't feel strongly about this, but I'd personally change it.

2021-04-20 17:40 UTC, carakessler commented on packages/cli/__tests__/cli-test.ts
> +    let outputPath = output.split(':')[1].trim(); // output will be a string followed by ':' then the file path
Sorry not a regex wizard here but there is a lot of path before the `my-checkup-file.json` we need to capture, and its all dynamic. Do you know how to do that? I can do some googling I suppose

2021-04-20 17:40 UTC, scalvert commented on packages/cli/__tests__/cli-test.ts
> +    let outputPath = output.split(':')[1].trim(); // output will be a string followed by ':' then the file path
Yes I do! Can you give me a pattern to match, like an example?

2021-04-20 18:49 UTC, carakessler commented on packages/cli/__tests__/cli-test.ts
> +    let outputPath = output.split(':')[1].trim(); // output will be a string followed by ':' then the file path
```
Results have been saved to the following file:
/private/var/folders/w6/8sjlbd7s3sjgj_s643kyhft0000bs0/T/tmp-40681ycH4rhsExFPi/checkup-app/my-checkup-file.json
```

2021-04-20 18:50 UTC, carakessler commented on packages/checkup-plugin-ember/src/formatters/ember-octane-migration-status-formatter.ts
> +export function format(taskResults: Result[], formatArgs: FormatArgs) {
call the type `args` or just the parameter?

2021-04-20 21:14 UTC, scalvert commented on packages/cli/__tests__/cli-test.ts
> +    let outputPath = output.split(':')[1].trim(); // output will be a string followed by ':' then the file path
Let's just split on the newline character and test the file path from that.

2021-04-20 21:14 UTC, scalvert commented on packages/checkup-plugin-ember/src/formatters/ember-octane-migration-status-formatter.ts
> +export function format(taskResults: Result[], formatArgs: FormatArgs) {
Just the param. That'd be an odd type name... :)

2021-04-20 21:18 UTC, scalvert approved these changes

2021-04-20 21:19 UTC, merged