Making paths an optional param in RunOptions, defaulting to `.`
checkupjs/checkup pull request #964
Opened 2021-04-28 21:58 UTC by carakessler

Giving paths a default value in RunOptions, used by CheckupTaskRunner

2021-04-28 23:06 UTC, scalvert requested changes

2021-04-28 23:06 UTC, scalvert commented on packages/core/src/types/cli.ts
> +  paths?: string[];
Sorry, why are we making `paths` optional? We should always require a path, right?

2021-04-28 23:13 UTC, carakessler commented on packages/core/src/types/cli.ts
> +  paths?: string[];
i thought we discussed the path being optional and defaulting it to `.`?

2021-04-29 00:53 UTC, scalvert commented on packages/core/src/types/cli.ts
> +  paths?: string[];
Just defaulting it, not the optional bit (unless I missed that). 

What does it mean to operate on no paths?

2021-04-29 00:54 UTC, scalvert commented on packages/core/src/types/cli.ts
> +  paths?: string[];
Also I think we need paths to be an array, in this case of one element.

2021-04-29 18:17 UTC, scalvert commented on packages/core/src/types/cli.ts
> +  paths?: string[];
We resolved this offline.

2021-04-29 18:17 UTC, scalvert approved these changes

2021-04-29 18:18 UTC, merged