WIP: Adding option to specify a pluginRoot directory
checkupjs/checkup pull request #995
Opened 2021-05-11 21:26 UTC by carakessler

We currently use the cwd prop used as "where do i look for the code to run checkup on" and "where should checkup look for the source code for the plugins". 

This PR adds in a new option to specify a directory for the latter, which is useful for running checkup via node api in a script run in the context of other repos.

2021-05-11 21:27 UTC, carakessler commented
This works (I've verified locally via `yarn link`ing, but I cant get a test that meaningfully checks this. I tried passing in random paths to `plugin-dir` but it somehow still finds them?? Dunno and would love some help and insights on how to best test this. I think I am lacking some knowledge about how `resolve.sync` works...

2021-05-11 23:28 UTC, carakessler commented on packages/cli/src/checkup.ts
> +              'The root directory where Checkup will load the plugins from. Defaults to cwd.',
done

2021-05-11 23:29 UTC, carakessler commented on packages/cli/src/checkup.ts
> +          pluginRoot: argv['plugin-root'] as string,
done

2021-05-11 23:29 UTC, carakessler commented on packages/core/src/types/cli.ts
> +  pluginRoot?: string;
done

2021-05-11 23:54 UTC, carakessler commented on packages/cli/__tests__/cli-test.ts
> +    let result = await run(['run', '.', '--plugin-root', 'some/random/dir']);
that is _kinda_ what i did but regardless your message gave me the brain blast i needed to write the test so yay!

2021-05-12 00:08 UTC, scalvert requested changes

2021-05-12 00:08 UTC, scalvert commented on packages/cli/__tests__/cli-test.ts
> +    let result = await run(['run', '.', '--plugin-base-dir', newProject.baseDir]);
Is this correct? You mean for the `--plugin-base-dir` to point to a project? I would've expected to have a `tmp`, generate the plugin inside that `tmp`, and use the `tmp` path as the `--plugin-base-dir`. Does that seem correct?

2021-05-12 18:04 UTC, scalvert requested changes

2021-05-12 18:04 UTC, scalvert commented on packages/cli/__tests__/cli-test.ts
> +    // project.dispose();
```suggestion
    project.dispose();
```

:)

2021-05-12 18:04 UTC, scalvert commented on packages/cli/src/api/checkup-task-runner.ts
> +    let pluginsLocation = this.options.pluginBaseDir || this.options.cwd;
```suggestion
    let pluginBaseDir = this.options.pluginBaseDir || this.options.cwd;
```

2021-05-12 18:04 UTC, scalvert commented on packages/cli/src/api/checkup-task-runner.ts
> +      let { register } = require(resolve.sync(pluginName, { basedir: pluginsLocation }));
```suggestion
      let { register } = require(resolve.sync(pluginName, { basedir: pluginBaseDir }));
```

2021-05-12 18:32 UTC, scalvert approved these changes

2021-05-12 18:32 UTC, merged